---
title: "Reproducible Research Assignment Week3 -- Report"
output: html_document
---
#Synopsis

#Introduction

Storms and other severe weather events can cause both public health and economic problems for communities and municipalities. Many severe events can result in fatalities, injuries, and property damage, and preventing such outcomes to the extent possible is a key concern.

This project involves exploring the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.

#Data Processing
The below code will download the file, unzip (in your work directory - check with getwd()) & create a data frame from it:
```{r}
fileurl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
download.file(url=fileurl,destfile="./repdata_data_StormData.csv.bz2",method="curl")
unzip("./repdata_data_StormData.csv.bz2")

#loading of data
repdata_data_StormData <- read.csv("./repdata_data_StormData.csv.bz2")

#grouping loss to population
repdata_data_StormData_summ <- repdata_data_StormData %>% select(EVTYPE,FATALITIES,INJURIES) %>% group_by(EVTYPE) %>% summarise_each(funs(sum)) %>% arrange(desc(FATALITIES,INJURIES))

#head
head_repdata_data_StormData_summ <- head(repdata_data_StormData_summ,10)
library(reshape2)
DF1 <- melt(head_repdata_data_StormData_summ, id.var="EVTYPE")
ggplot(DF1, aes(x = reorder(EVTYPE), y = value, fill = variable)) + 
    geom_bar(stat = "identity")

```



##Plot


#Result

1. Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

2. Across the United States, which types of events have the greatest economic consequences?

